SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'BEGIN NULL; END;';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER APP_USER IDENTIFIED BY app_user';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -01920 OR SQLCODE = -01918 OR SQLCODE = -01921 OR SQLCODE = -01955 THEN
            NULL; -- user exists or other benign error
        ELSE
            RAISE;
        END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, UNLIMITED TABLESPACE TO APP_USER';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'ALTER USER APP_USER QUOTA UNLIMITED ON USERS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
-- Ensure APP_USER has privileges to allow the application to operate
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.DUAL TO APP_USER';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
