spring.application.name=mts_service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mts_db?sslmode=disable&stringtype=unspecified}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.docker.compose.enabled=false

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

payments.base-url=https://payments.example.com/mock-pay

# Pagination
app.pagination.default-limit=20

# Currency
app.currency.code=RUB

# Mock authentication
app.auth.mock-header=X-Mock-User
app.auth.default-user=mock@local
app.auth.manager-user=manager@local
app.auth.admin-user=admin@local

# User ID header
app.auth.user-id-header=X-User-Id

# Security public endpoints
app.security.public-post-endpoints=/api/users
app.security.public-endpoints=/error
