# Primary DB (Postgres #1)
app.datasource.primary.url=jdbc:postgresql://localhost:5432/primarydb
app.datasource.primary.username=primary_user
app.datasource.primary.password=primary_pass

# Balance DB (Postgres #2)
app.datasource.balance.url=jdbc:postgresql://localhost:5433/balancedb
app.datasource.balance.username=balance_user
app.datasource.balance.password=balance_pass

# JPA / JTA settings
spring.jpa.transaction-type=JTA
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NarayanaJtaPlatform
spring.jta.narayana.log-dir=./target/narayana/logs
spring.jta.enabled=true

